apiVersion: v1
kind: Service
metadata:
  name: unity-go-app
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: unity-go-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: unity-go-app
  template:
    metadata:
      labels:
        app: unity-go-app
    spec:
      containers:
      - name: unity-go-app
        image: unity-go-app